services:
  integ-test:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8081:8080"
    environment:
      - PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}
      - RUN_ID=Test123
      # - TEST_RUN=True
      - AWS_REGION=eu-central-1
      - MODEL_LOCATION=/app/model
      - KINESIS_ENDPOINT_URL=http://kinesis:4566
    volumes:
      - "/home/onur/.aws:/root/.aws"
      - "${PWD}/model:/app/model"
  kinesis:
    image: localstack/localstack
    ports:
      - "4566:4566" 
    environment:
      - SERVICES=kinesis
