services:
  integ-test:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8081:8080"
    environment:
      - S3_ENDPOINT_URL=http://localhost:4566
    volumes:
      - "/home/onur/.aws:/root/.aws"
      - "${PWD}/model:/app/model"
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566" 
    environment:
      - SERVICES=s3